project:
  type: website
  output-dir: docs

website:
  navbar:
    left:
      - href: index.qmd
        text: Home
      - Publications.qmd
      - Talks.qmd
  page-footer:  ## 页脚设置
    background: "#ccccd6"
    center: 
      - text: 'About'
        href: about.qmd
        
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

